# Generated by Django 4.2.3 on 2023-07-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipoconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
                ('tipo_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoconsulta')),
            ],
        ),
    ]
