# Generated by Django 4.2.3 on 2023-07-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
